# These are supported funding model platforms

#github: [nsherbina1999]
ko_fi: mykytashcherbyna
buy_me_a_coffee: nsherbina1999
thanks_dev: nsherbina1999
patreon: mykytashcherbyna
custom: ['https://www.paypal.com/donate/?hosted_button_id=9ETHFD5CQZVHL']
