name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x86, x64]

    steps:
    - uses: actions/checkout@v4

    - name: Cache WAF Build Files
      uses: actions/cache@v4
      with:
        path: |
          build
          .waf*
          .lock-waf*
        key: ${{ runner.os }}-waf-${{ matrix.arch }}-${{ github.sha }}

    - name: Cache Submodules
      uses: actions/cache@v4
      with:
        path: |
          .git/modules
        key: ${{ runner.os }}-submodules-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-submodules-

    - name: Setup Submodules
      run: |
        git submodule init && git submodule update
      shell: pwsh

    - name: Create Output Directory
      run: |
        if (!(Test-Path -Path "out")) {
          New-Item -ItemType Directory -Path "out"
        }
      shell: pwsh

    - name: Build on Windows
      run: |
        if ($env:matrix_arch -eq 'x86') {
          ./waf.bat configure -T debug --32bits
        } else {
          ./waf.bat configure -T debug
        }
        ./waf.bat build
      shell: pwsh
