name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-2019, macos-latest]
        arch: [i386, amd64, armv7a]
        dedicated: [false, true]
    steps:
    - uses: actions/checkout@v4

    - name: Build on Linux
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-20.04'
      shell: bash
      run: |
        git submodule init && git submodule update
        if [ "${{ matrix.arch }}" = "i386" ]; then
          if [ "${{ matrix.dedicated }}" = "true" ]; then
            scripts/build-ubuntu-i386.sh -d
          else
            scripts/build-ubuntu-i386.sh
          fi
        elif [ "${{ matrix.arch }}" = "amd64" ]; then
          if [ "${{ matrix.dedicated }}" = "true" ]; then
            scripts/build-ubuntu-amd64.sh -d
          else
            scripts/build-ubuntu-amd64.sh
          fi
        elif [ "${{ matrix.arch }}" = "armv7a" ]; then
          scripts/build-android-armv7a.sh
        fi

    - name: Build on Windows
      if: matrix.os == 'windows-2019'
      shell: powershell
      run: |
        git submodule init && git submodule update
        if [ "${{ matrix.arch }}" == "i386" ]; then
          if [ "${{ matrix.dedicated }}" == "true" ]; then
            ./waf.bat configure -T debug --32bits -d
          else
            ./waf.bat configure -T debug --32bits
          fi
        elif [ "${{ matrix.arch }}" == "amd64" ]; then
          if [ "${{ matrix.dedicated }}" == "true" ]; then
            ./waf.bat configure -T debug -d
          else
            ./waf.bat configure -T debug
          fi
        fi
        ./waf.bat build

    - name: Build on macOS
      if: matrix.os == 'macos-latest' && matrix.arch == 'amd64'
      run: |
        if [ "${{ matrix.dedicated }}" == "true" ]; then
          scripts/build-macos-amd64.sh -d
        else
          scripts/build-macos-amd64.sh
        fi
